envVarGroups:
  - name: mealhub-common
    envVars:
      - key: APP_KEY
        sync: false

services:
  - type: web
    name: mealhub-web
    env: php
    rootDirectory: src/mealhub
    buildCommand: |
      # 只安裝 PHP 依賴；目前不需前端建置（純 API）
      composer install --no-dev --optimize-autoloader
    startCommand: bash render-start.sh
    autoDeploy: true
    healthCheckPath: /
    envVarGroups:
      - mealhub-common
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: LOG_STDERR_FORMATTER
        value: Monolog\\Formatter\\JsonFormatter
      # 若未設定，啟動腳本會以 RENDER_EXTERNAL_URL 帶入
      - key: APP_URL
        value: https://example.onrender.com
      # 使用 Render 受管 Postgres
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: mealhub-db
          property: connectionString
      # 使用 Redis（predis 客戶端，無需安裝擴充）
      - key: REDIS_CLIENT
        value: predis
      - key: REDIS_URL
        fromService:
          name: mealhub-redis
          type: redis
          property: connectionString
      # 將快取/Session 切到 Redis；Queue 使用 Redis
      - key: CACHE_STORE
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: QUEUE_CONNECTION
        value: redis

  - type: worker
    name: mealhub-worker
    env: php
    rootDirectory: src/mealhub
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    autoDeploy: true
    envVarGroups:
      - mealhub-common
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: LOG_STDERR_FORMATTER
        value: Monolog\\Formatter\\JsonFormatter
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: mealhub-db
          property: connectionString
      - key: REDIS_CLIENT
        value: predis
      - key: REDIS_URL
        fromService:
          name: mealhub-redis
          type: redis
          property: connectionString
      - key: QUEUE_CONNECTION
        value: redis

  - type: worker
    name: mealhub-scheduler
    env: php
    rootDirectory: src/mealhub
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: php artisan schedule:work
    autoDeploy: true
    envVarGroups:
      - mealhub-common
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: LOG_STDERR_FORMATTER
        value: Monolog\\Formatter\\JsonFormatter
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: mealhub-db
          property: connectionString
      - key: REDIS_CLIENT
        value: predis
      - key: REDIS_URL
        fromService:
          name: mealhub-redis
          type: redis
          property: connectionString

databases:
  - name: mealhub-db
    plan: free

redis:
  - name: mealhub-redis
    plan: free
